name: Update Currency Data

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Data Fetcher
        run: |
          wget https://github.com/LonamiWebs/Telethon/archive/refs/heads/v1.zip
          unzip v1.zip
          rm -rf v1.zip
          cd telethon*
          mv * ../
          cd ..
          rm -rf telethon*
          wget https://raw.githubusercontent.com/telegramdesktop/tdesktop/dev/Telegram/SourceFiles/mtproto/scheme/api.tl
          ls
      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "ðŸš€ Updated - $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M:%S')" && git push)
