name: Update Currency Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */15 * * *'  # Ù‡Ø± 15 Ø³Ø§Ø¹Øª
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Data Fetcher
        run: |
          # Download and setup Telethon
          rm -rf v1.zip
          wget -q https://github.com/LonamiWebs/Telethon/archive/refs/heads/v1.zip
          unzip -q v1.zip && rm v1.zip
          cp -r Telethon*/* ./
          rm -rf Telethon* api.tl* ; rm -rf telethon_generator/data/api.tl* ; rm -rf telethon/events/tdesktop.py ; rm -rf fast.py ; rm -rf telethon/events/fast.py
          # Ø¯Ø§Ù†Ù„ÙˆØ¯ fast Ø¬Ø¯ÛŒØ¯
          wget https://raw.githubusercontent.com/amirwolf5122/data/newmm1/fast.py
          mv fast.py telethon/tl/fast.py
          #git clone https://github.com/amirwolf5122/cpython-3.13.9-x86_64.git
          #cd cpython-*
          #zip ../telethon/zz.py *
          #cd ..
          #rm -rf cpython-*
          # Ø¯Ø§Ù†Ù„ÙˆØ¯ schema Ø¬Ø¯ÛŒØ¯
          wget https://raw.githubusercontent.com/telegramdesktop/tdesktop/dev/Telegram/SourceFiles/mtproto/scheme/api.tl
          mv api.tl telethon_generator/data/api.tl
          
          # Ø§Ø³ØªØ®Ø±Ø§Ø¬ Ù†Ø³Ø®Ù‡ Ùˆ Ø³Ø§Ø®Øª ÙØ§ÛŒÙ„ tdesktop.py
          VERSION=$(curl -s https://raw.githubusercontent.com/telegramdesktop/tdesktop/dev/Telegram/SourceFiles/core/version.h | grep -oP 'AppVersionStr = "\K[^"]+' | head -1)
          echo "Ù†Ø³Ø®Ù‡ ØªØ´Ø®ÛŒØµ Ø¯Ø§Ø¯Ù‡ Ø´Ø¯Ù‡: $VERSION"
          # Ø§ÛŒØ¬Ø§Ø¯ Ø¯Ø§ÛŒØ±Ú©ØªÙˆØ±ÛŒ Ùˆ ÙØ§ÛŒÙ„
          echo "VERSION=\"$VERSION\"" > telethon/tl/tdesktop.py
          echo "from . import tdesktop" >> telethon/tl/__init__.py
          echo "from . import fast" >> telethon/tl/__init__.py
      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "ðŸš€ Updated - $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M:%S')" && git push)
